export const FETCH_PROJECTS = "FETCH_PROJECTS";
export const FETCH_PROJECTS_FULFILLED = "FETCH_PROJECTS_FULFILLED";
export const FETCH_PROJECTS_REJECTED = "FETCH_PROJECTS_REJECTED";
export const FETCH_PROJECTS_PENDING = "FETCH_PROJECTS_PENDING";

export const FETCH_PROJECT = "FETCH_PROJECT";
export const FETCH_PROJECT_FULFILLED = "FETCH_PROJECT_FULFILLED";
export const FETCH_PROJECT_REJECTED = "FETCH_PROJECT_REJECTED";
export const FETCH_PROJECT_PENDING = "FETCH_PROJECT_PENDING";
