export const FETCH_PROJECTS = 'FETCH_PROJECTS'
export const FETCH_PROJECTS_FULFILLED = 'FETCH_PROJECTS_FULFILLED'
export const FETCH_PROJECTS_REJECTED = 'FETCH_PROJECTS_REJECTED'
export const FETCH_PROJECTS_PENDING = 'FETCH_PROJECTS_PENDING'

export const FETCH_PROJECT = 'FETCH_PROJECT'
export const FETCH_PROJECT_FULFILLED = 'FETCH_PROJECT_FULFILLED'
export const FETCH_PROJECT_REJECTED = 'FETCH_PROJECT_REJECTED'
export const FETCH_PROJECT_PENDING = 'FETCH_PROJECT_PENDING'

export const CREATE_PROJECT = 'CREATE_PROJECT'
export const CREATE_PROJECT_FULFILLED = 'CREATE_PROJECT_FULFILLED'
export const CREATE_PROJECT_REJECTED = 'CREATE_PROJECT_REJECTED'
export const CREATE_PROJECT_PENDING = 'CREATE_PROJECT_PENDING'

export const UPDATE_PROJECT = 'UPDATE_PROJECT'
export const UPDATE_PROJECT_FULFILLED = 'UPDATE_PROJECT_FULFILLED'
export const UPDATE_PROJECT_REJECTED = 'UPDATE_PROJECT_REJECTED'
export const UPDATE_PROJECT_PENDING = 'UPDATE_PROJECT_PENDING'

export const REMOVE_PROJECT = 'REMOVE_PROJECT'
export const REMOVE_PROJECT_FULFILLED = 'REMOVE_PROJECT_FULFILLED'
export const REMOVE_PROJECT_REJECTED = 'REMOVE_PROJECT_REJECTED'
export const REMOVE_PROJECT_PENDING = 'FETCH_PROJECT_PENDING'
